// <auto-generated />
namespace BookRental.DataAccess.Configurations.Migration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class firstSeedrn : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(firstSeedrn));
        
        string IMigrationMetadata.Id
        {
            get { return "201908171830584_firstSeedrn"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
